# Generated by Django 4.0.4 on 2022-06-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
