# Generated by Django 4.0.4 on 2022-06-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0011_alter_users_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ['-dat_of_pub', 'title'], 'verbose_name': 'Advert'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User'},
        ),
    ]
